# Generated by Django 2.1.3 on 2018-12-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0002_auto_20181219_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_classe',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
