# Generated by Django 2.1.3 on 2018-12-24 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0003_auto_20181223_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='user',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='user',
        ),
        migrations.DeleteModel(
            name='Classe',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
