# Generated by Django 2.1.3 on 2019-02-09 08:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0005_auto_20190206_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='current_classe',
            new_name='classe',
        ),
    ]
