# Generated by Django 2.1.3 on 2019-02-09 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0006_auto_20190209_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
