# Generated by Django 2.1.3 on 2019-02-12 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0007_user_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='notes',
            field=models.TextField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
