# Generated by Django 2.1.3 on 2019-04-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0008_auto_20190212_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default=None, help_text='Apponi sempre +39 prima del numero',
                                   max_length=20, null=True, verbose_name='Cellulare'),
        ),
    ]
