# Generated by Django 2.1.3 on 2019-04-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0009_auto_20190405_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, default=None,
                                   help_text='La data di nascita è richiesta per il rispetto delle norme vigenti sulla privacy.',
                                   null=True, verbose_name='Data di nascita'),
        ),
    ]
