# Generated by Django 2.1.3 on 2019-10-09 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0012_user_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
