# Generated by Django 2.1.3 on 2019-10-23 12:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0014_auto_20191023_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='short_full_name',
        ),
    ]
