# Generated by Django 2.1.3 on 2019-10-24 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0015_remove_user_short_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'utente', 'verbose_name_plural': 'utenti'},
        ),
    ]
