# Generated by Django 2.1.3 on 2019-10-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0018_auto_20191028_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
