# Generated by Django 2.1.3 on 2018-12-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
