# Generated by Django 2.1.3 on 2018-12-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0002_activity_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='hidden',
        ),
        migrations.AddField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
