# Generated by Django 2.1.3 on 2018-12-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0003_auto_20181221_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='default_end_time',
            field=models.TimeField(default='16:30:00'),
        ),
        migrations.AddField(
            model_name='subject',
            name='default_start_time',
            field=models.TimeField(default='15:00:00'),
        ),
    ]
