# Generated by Django 2.1.3 on 2018-12-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0004_auto_20181221_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='default_teacher',
            field=models.CharField(blank=True, default=None, max_length=35, null=True),
        ),
    ]
