# Generated by Django 2.1.3 on 2019-01-04 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0005_subject_default_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='activity',
            name='end_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='start_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
