# Generated by Django 2.1.3 on 2019-01-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('activities', '0006_auto_20190104_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='groups',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
