# Generated by Django 2.1.3 on 2019-01-12 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0007_activity_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='school_year',
        ),
    ]
