# Generated by Django 2.1.3 on 2019-01-25 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0009_meeting_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='reservations_count',
        ),
    ]
