# Generated by Django 2.1.3 on 2019-02-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0012_participation_is_justified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='deleted',
        ),
        migrations.AddField(
            model_name='meeting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
