# Generated by Django 2.1.3 on 2019-03-10 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0014_presencetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='presence_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                    to='activities.PresenceType'),
        ),
    ]
