# Generated by Django 2.1.3 on 2019-09-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0021_subject_offers_asl'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='applications_open',
            field=models.BooleanField(default=False),
        ),
    ]
