# Generated by Django 2.1.3 on 2019-09-21 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0023_activity_meetings_open'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='applications_open',
            new_name='are_applications_active',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='meetings_open',
            new_name='are_meetings_active',
        ),
    ]
