# Generated by Django 2.1.3 on 2019-09-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0024_auto_20190921_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='classe',
            field=models.CharField(blank=True, default=None, max_length=3, null=True),
        ),
    ]
