# Generated by Django 2.1.3 on 2019-10-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0029_auto_20191006_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='widths',
            field=models.CharField(default='9,3', max_length=10),
        ),
    ]
