# Generated by Django 2.1.3 on 2019-10-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0031_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='are_registrations_active',
            field=models.BooleanField(default=False),
        ),
    ]
