# Generated by Django 2.1.3 on 2019-11-04 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0034_defaultassigneduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultassigneduser',
            name='subject',
            field=models.ForeignKey(default=56, on_delete=django.db.models.deletion.CASCADE, to='activities.Subject'),
            preserve_default=False,
        ),
    ]
