# Generated by Django 2.1.3 on 2019-11-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0035_defaultassigneduser_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencetype',
            name='text_class',
            field=models.CharField(default='success', max_length=50),
            preserve_default=False,
        ),
    ]
