# Generated by Django 2.1.3 on 2019-11-22 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0037_auto_20191118_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participation',
            name='topic',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
