# Generated by Django 2.1.3 on 2019-11-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0038_auto_20191122_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='is_absent_morning',
            field=models.BooleanField(default=False),
        ),
    ]
