# Generated by Django 3.0 on 2019-12-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0041_participation_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='start_at',
        ),
        migrations.AddField(
            model_name='activity',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
