# Generated by Django 3.0 on 2019-12-21 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0043_auto_20191221_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingsGenerationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_meetings', models.PositiveIntegerField()),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activities.Subject')),
            ],
        ),
    ]
