# Generated by Django 3.0 on 2019-12-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0044_meetingsgenerationoption'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingsgenerationoption',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='meetingsgenerationoption',
            name='start_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='meetingsgenerationoption',
            name='number_of_meetings',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
