# Generated by Django 3.0 on 2019-12-21 22:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0045_auto_20191221_2314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingsgenerationoption',
            options={'verbose_name': 'opzione generazione incontri',
                     'verbose_name_plural': 'opzioni generazione incontri'},
        ),
    ]
