# Generated by Django 3.0 on 2020-01-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0046_auto_20191221_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='default_teacher',
        ),
        migrations.AlterField(
            model_name='activity',
            name='allow_new_reservations',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='allow_student_topics',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='allow_teacher_topics',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='are_meetings_active',
            field=models.BooleanField(default=True),
        ),
    ]
