# Generated by Django 3.0 on 2020-01-24 10:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0047_auto_20200109_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='code',
        ),
    ]
