# Generated by Django 3.0 on 2020-01-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0048_remove_subject_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
