# Generated by Django 3.0 on 2020-02-27 17:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0051_auto_20200226_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participationgroup',
            name='is_active',
        ),
    ]
