# Generated by Django 3.0 on 2020-04-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('activities', '0052_remove_participationgroup_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='weekdays',
            field=models.ManyToManyField(blank=True, to='activities.Weekday'),
        ),
    ]
