# Generated by Django 3.0.8 on 2020-09-01 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0053_auto_20200405_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='allow_event_overlapping',
            field=models.BooleanField(default=True),
        ),
    ]
