# Generated by Django 3.0.8 on 2020-09-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0054_activity_allow_event_overlapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='default_end_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='default_start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
